CREATE TABLE IF NOT EXISTS categories(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    icon text
);

CREATE TABLE IF NOT EXISTS properties(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    categoryProperty INTEGER REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS vehicles(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    patent text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS propertyValues(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value integer NOT NULL,
    valueVehicle integer REFERENCES vehicles(id),
    valueProperty integer REFERENCES properties(id)
);





-- INSERT VEHICLES CATEGORIES

INSERT INTO categories(name, icon)
    VALUES('Documentos','https://img.icons8.com/ios/50/000000/document.png');

INSERT INTO categories(name, icon)
    VALUES('Motor','https://img.icons8.com/ios/50/000000/engine.png');

INSERT INTO categories(name, icon)
    VALUES('Ruedas y frenos','https://img.icons8.com/fluency/48/000000/wheel.png');

INSERT INTO categories(name, icon)
    VALUES('Exterior','https://img.icons8.com/dotty/80/000000/car.png');

-- INSER PROPERTY DATA

INSERT INTO properties(name, categoryProperty)
    VALUES('Cédula verde, azul',1);

INSERT INTO properties(name, categoryProperty)
    VALUES('VTV vigente',1);

INSERT INTO properties(name, categoryProperty)
    VALUES('Deudas',1);

INSERT INTO properties(name, categoryProperty)
    VALUES('Verificacion Policial',1);

INSERT INTO properties(name, categoryProperty)
    VALUES('Estado General',2);

INSERT INTO properties(name, categoryProperty)
    VALUES('Ruidos',2);

INSERT INTO properties(name, categoryProperty)
    VALUES('Estado de aceite',2);

INSERT INTO properties(name, categoryProperty)
    VALUES('Ruedas Delanteras',3);

INSERT INTO properties(name, categoryProperty)
    VALUES('Ruedas Traseras',3);

INSERT INTO properties(name, categoryProperty)
    VALUES('Frenos Delanteros',3);

INSERT INTO properties(name, categoryProperty)
    VALUES('Frenos Traseros',3);

INSERT INTO properties(name, categoryProperty)
    VALUES('Pintura',4);

INSERT INTO properties(name, categoryProperty)
    VALUES('Luces',4);

-- INSERT VEHICLES DATA
INSERT INTO vehicles(name, patent)
    VALUES('Volkswagen Gol', '001-abc');

INSERT INTO vehicles(name, patent)
    VALUES('Renault Sandero', '002-abc');

INSERT INTO vehicles(name, patent)
    VALUES('Toyota Etios', '003-abc');

--INSERT PROPERTYVALUE DATA


INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,1);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,2);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,3);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,4);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,5);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,6);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,7);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,8);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,9);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,10);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,11);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,12);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,1,13);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,1);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,2);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,3);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,4);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,5);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,6);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,7);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,8);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,9);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,10);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,11);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,12);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,2,13);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,1);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,2);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,3);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,4);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,5);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,6);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,7);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,8);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,9);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,10);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,11);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,12);

INSERT INTO propertyValues(value,valueVehicle,valueProperty)
    VALUES(1,3,13);