CREATE TABLE IF NO EXIST vehicles(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    icon text,
);

CREATE TABLE IF NOT EXIST categories(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    icon text,
    vehicleId INTEGER REFERENCES vehicles(id)
);

CREATE TABLE IF NOT EXIST properties(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    icon text,
    vehicleId INTEGER REFERENCES vehicles(id)
);